name: ENTSO-E Daily Fetcher

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Важливо: дозвіл на запис файлів
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          ENTSOE_TOKEN: ${{ secrets.ENTSOE_TOKEN }}
        run: python main.py

      - name: Commit and Push CSV
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add prices_history.csv
          git commit -m "Update prices history [skip ci]" || exit 0
          git push
